name = "IdealizedSphericalWeatherModel"
uuid = "33232268-8d85-464a-bf3a-49ac619dc9b4"
authors = ["Jesse <jesbrirob@gmail.com>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
